/*
 * Copyright 2025 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.pixollage.ui;

import java.io.File;
import java.io.IOException;
import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.StringUtils;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.filesystems.FileUtil;
import org.openide.util.Exceptions;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;
import se.trixon.pixollage.Pixollage;
import se.trixon.pixollage.collage.Collage;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//se.trixon.pixollage.main.ui//Collage//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "CollageTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ONLY_OPENED
)
public final class CollageTopComponent extends TopComponent {

    private Collage mCollage;
    private CollageSavable mCollageSavable;
    private final InstanceContent mInstanceContent = new InstanceContent();

    public CollageTopComponent() {
        initComponents();
        mCollage = new Collage();
        collageTopComponent();
        modify();
    }

    public CollageTopComponent(Collage collage) {
        initComponents();
        mCollage = collage;
        collageTopComponent();
    }

    @Override
    public boolean canClose() {
        boolean canClose;
        if (getLookup().lookupAll(CollageSavable.class).stream().anyMatch(c -> c == mCollageSavable)) {
            //TODO Display Save, Discard & Cancel dialog
            //Loop?
            canClose = false;
        } else {
            canClose = true;
        }

        if (canClose) {
//            resetSavable();
        }

        return canClose;
    }

    public void collageTopComponent() {
        mCollage.setTopComponent(this);
        loadCollage();
        try {
            associateLookup(new AbstractLookup(mInstanceContent));
        } catch (IllegalStateException e) {
            //nvm - already set
        }
        mInstanceContent.add(mCollage);
    }

    @Override
    public int getPersistenceType() {
        if (mCollage.getFile() == null) {
            return TopComponent.PERSISTENCE_NEVER;
        } else {
            return TopComponent.PERSISTENCE_ONLY_OPENED;
        }
    }

    public void refreshNames() {
        setName(mCollage.getName());
        if (mCollage.getFileObject() != null) {
            setToolTipText(mCollage.getFileObject().getPath());
        }
    }

    public void resetSavable() {
        getInstanceContent().remove(mCollageSavable);
        mCollageSavable.removeFromRegistry();
    }

    private void loadCollage() {
        refreshNames();
        collagePanel.load(mCollage);
    }

    public Collage getCollage() {
        return mCollage;
    }

    public InstanceContent getInstanceContent() {
        return mInstanceContent;
    }

    public void modify() {
        if (getLookup().lookup(CollageSavable.class) == null) {
            mCollageSavable = new CollageSavable(CollageTopComponent.this);
            mInstanceContent.add(mCollageSavable);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        collagePanel = new se.trixon.pixollage.ui.CollagePanel();

        setBackground(new java.awt.Color(255, 255, 153));
        setLayout(new java.awt.BorderLayout());

        collagePanel.setLayout(null);
        add(collagePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private se.trixon.pixollage.ui.CollagePanel collagePanel;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO showAddImageDialog custom code on component opening
    }

    @Override
    public void componentClosed() {
        System.out.println("componentClosed");
//        resetSavable();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
        var file = mCollage.getFile();
        if (file != null) {
            p.put("path", file.getAbsolutePath());
        }
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version

        String path = p.getProperty("path");

        if (StringUtils.isNotBlank(path) && new File(path).isFile()) {
            var file = new File(path);
            try {
                loadFromFile(file);
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }
        }
    }

    private void loadFromFile(File file) throws IOException {
        mInstanceContent.remove(mCollage);
        var fileObject = FileUtil.createData(file);
        mCollage = Pixollage.GSON.fromJson(FileUtils.readFileToString(file, "utf-8"), Collage.class);
        mCollage.setFileObject(fileObject);
        collageTopComponent();
    }
}
