/*
 * Copyright 2025 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.pixollage.ui;

import se.trixon.almond.util.Dict;
import se.trixon.pixollage.collage.CollageProperties;

/**
 *
 * @author Patrik Karlström <patrik@trixon.se>
 */
public class RenderPanel extends javax.swing.JPanel {

    private boolean mEnabledHeightAdjust = true;
    private boolean mEnabledWidthAdjust = true;
    private CollageProperties mProperties;

    /**
     * Creates new form RenderPanel
     */
    public RenderPanel() {
        initComponents();
    }

    public void apply(CollageProperties properties) {

    }

    public void load(CollageProperties properties) {
        mProperties = properties;

        widthSpinner.setValue(mProperties.getRenderWidth() + 1);
        widthSpinner.setValue(mProperties.getRenderWidth() - 1);

        if (mProperties.getRenderPath() != null) {
            fileChooserPanel.setPath(mProperties.getRenderPath().getAbsolutePath());
        }

        ratioValueLabel.setText("%d : %d".formatted(mProperties.getAspectRatioWidth(), mProperties.getAspectRatioHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserPanel = new se.trixon.almond.util.swing.dialogs.FileChooserPanel();
        widthLabel = new javax.swing.JLabel();
        widthSpinner = new javax.swing.JSpinner();
        heightLabel = new javax.swing.JLabel();
        heightSpinner = new javax.swing.JSpinner();
        ratioHeaderLabel = new javax.swing.JLabel();
        ratioValueLabel = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(widthLabel, Dict.Geometry.WIDTH.toString());

        widthSpinner.setModel(new javax.swing.SpinnerNumberModel(100, 100, null, 10));
        widthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                widthSpinnerStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(heightLabel, Dict.Geometry.HEIGHT.toString());

        heightSpinner.setModel(new javax.swing.SpinnerNumberModel(100, 10, null, 10));
        heightSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightSpinnerStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(ratioHeaderLabel, org.openide.util.NbBundle.getMessage(RenderPanel.class, "PropertiesPanel.ratioLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(ratioValueLabel, "W:H"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileChooserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(widthLabel)
                            .addComponent(widthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heightSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(heightLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ratioValueLabel)
                            .addComponent(ratioHeaderLabel))
                        .addGap(142, 142, 142)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(widthLabel)
                        .addGap(0, 0, 0)
                        .addComponent(widthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heightLabel)
                            .addComponent(ratioHeaderLabel))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ratioValueLabel))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void widthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_widthSpinnerStateChanged
        if (!mEnabledWidthAdjust) {
            return;
        }
        mProperties.setRenderWidth((int) widthSpinner.getValue());
        mProperties.calculateRenderHeight();
        mEnabledHeightAdjust = false;
        heightSpinner.setValue(mProperties.getRenderHeight());
        mEnabledHeightAdjust = true;

    }//GEN-LAST:event_widthSpinnerStateChanged

    private void heightSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heightSpinnerStateChanged
        if (!mEnabledHeightAdjust) {
            return;
        }
        mProperties.setRenderHeight((int) heightSpinner.getValue());
        mProperties.calculateRenderWidth();
        mEnabledWidthAdjust = false;
        widthSpinner.setValue(mProperties.getRenderWidth());
        mEnabledWidthAdjust = true;
    }//GEN-LAST:event_heightSpinnerStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private se.trixon.almond.util.swing.dialogs.FileChooserPanel fileChooserPanel;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JSpinner heightSpinner;
    private javax.swing.JLabel ratioHeaderLabel;
    private javax.swing.JLabel ratioValueLabel;
    private javax.swing.JLabel widthLabel;
    private javax.swing.JSpinner widthSpinner;
    // End of variables declaration//GEN-END:variables
}
